### ISSUE TITLE
Compilation failure: can not resolve parent

### ISSUE THREAD

**Issue by peterbecker** [mulesoft/mule-agent-modules#5]
When trying to build this with `mvn compile` I get:

    [FATAL] Non-resolvable parent POM for com.mulesoft.agent:mule-agent-modules:[unknown-version]: Could not find artifact com.mulesoft.agent:mule-agent-common:pom:1.0.1-SNAPSHOT in all-repos

The top-level POM declares:

    <parent>
        <artifactId>mule-agent-common</artifactId>
        <groupId>com.mulesoft.agent</groupId>
        <version>1.0.1-SNAPSHOT</version>
    </parent>

I can't find anything with that groupId in Maven Central nor the Mule Enterprise repository. I can't find a matching GitHub project to build it myself either.

Given that the POM doesn't declare a version for itself it seems like a module was extracted from a larger context that I can't find.

**Comment by josesahad** [comment]
Hi Peter,
just updated the README, you should be able to compile 1.2.0 with access to Mule EE repository.

Thanks

**Comment by josesahad** [comment]
Closing the issue, please reopen if it's not working for you yet.
BR
