### ISSUE TITLE
Installing Mule-Agent

### ISSUE THREAD

**Issue by jdorney0107** [mulesoft/mule-agent-modules#51]
I'm trying to install mule-agent 1.4.0 to my Mule ESB 3.7.3. I extracted the mule-agent.zip into the MULE_HOME/bin and ran the command amc_setup -U to update the agent. This was successful. I created a java keystore. I then created a mule-agent.yml file in the MULE_HOME/conf directory. The contents are

muleInstanceUniqueId: validId
organizationId: organizationId

transports:
rest.agent.transport:
security:
keyStorePassword: passw0rd
keyStoreAlias: mule
keyStoreAliasPassword: passw0rd
port: 9997

services:
mule.agent.application.service:
enabled: true

mule.agent.domain.service:
enabled: true

mule.agent.jmx.publisher.service:
enabled: true
frequency: 15
frequencyTimeUnit: MINUTES
beans:

beanQueryPattern: java.lang:type=Runtime attribute: Uptime monitorMessage: Monitoring memory up-time
beanQueryPattern: java.lang:type=MemoryPool,* attribute: Usage.used monitorMessage" : Used Memory
internalHandlers:
domaindeploymentnotification.internal.message.handler:
enabled: false

applicationdeploymentnotification.internal.message.handler:
enabled: false

When I try to start my Mule ESB I get an error saying the web uri is empty. So I added the web url. My file now looks like this.

muleInstanceUniqueId: validId
organizationId: organizationId

transports:
websocket.transport:
consoleUri: wss://localhost:443/mule
security:
keyStorePassword: golfer
keyStoreAlias: agent
keyStoreAliasPassword: golfer
rest.agent.transport:
port: 8888

services:
mule.agent.application.service:
enabled: true

mule.agent.domain.service:
enabled: true

mule.agent.jmx.publisher.service:
enabled: true
frequency: 15
frequencyTimeUnit: MINUTES
beans:

beanQueryPattern: java.lang:type=Runtime attribute: Uptime monitorMessage: Monitoring memory up-time
beanQueryPattern: java.lang:type=MemoryPool,* attribute: Usage.used monitorMessage" : Used Memory
internalHandlers:
domaindeploymentnotification.internal.message.handler:
enabled: false

applicationdeploymentnotification.internal.message.handler:
enabled: false

I now get the error

mule_agent.log:ERROR 2016-07-06 12:29:38,149 [WrapperListener_start_runner] com.mulesoft.agent.AgentTransportManager: Could not initialise the transport: WebSocketAgentTransport: Could not initialise WebSocket Client: The socket could not be created
mule_ee.log:ERROR 2016-07-06 12:29:38,149 [WrapperListener_start_runner] com.mulesoft.agent.AgentTransportManager: Could not initialise the transport: WebSocketAgentTransport: Could not initialise WebSocket Client: The socket could not be created

I've changed the wss to http in the url but still no joy.

I can't seem to find any documentation on the mule-agent.yml file that describes what the fields mean.

Any help would be appreciated.

**Comment by wpoch** [comment]
Hi @jdorney0107, are you planning to use the REST Transport? or do you want to manage your On-Prem Mule ESB using our Anypoint Platform Runtime Manager (https://anypoint.mulesoft.com/accounts/)? the later option is what I recommend you.

Anyway here are the docs regarding the Mule Agent: https://docs.mulesoft.com/mule-agent/v/1.4.0/installing-mule-agent

Regards,
