### ISSUE TITLE
Maven build depends on internal repo

### ISSUE THREAD

**Issue by adrianhsieh** [mulesoft/mule-agent-modules#52]
mvn clean install

Leads to error:
[ERROR] Failed to execute goal on project mule-agent-modules-common: Could not resolve dependencies for project com.mulesoft.agent:mule-agent-modules-common:jar:1.4.0: Failed to collect dependencies at com.mulesoft.agent:mule-agent-api:jar:1.4.0: Failed to read artifact descriptor for com.mulesoft.agent:mule-agent-api:jar:1.4.0: Could not transfer artifact com.mulesoft.agent:mule-agent-api:pom:1.4.0 from/to mule-ee-snapshots (https://repository-master.mulesoft.org/nexus/content/repositories/ci-snapshots/): Not authorized , ReasonPhrase:Unauthorized. 

This repo is internal, 403 for outside developers:
https://repository-master.mulesoft.org/nexus/content/repositories/ci-snapshots/

**Comment by wpoch** [comment]
Hi @adrianhsieh, seems we missed the artifacts on our MuleSoft Releases repository (https://repository-master.mulesoft.org/nexus/content/repositories/releases-ee/). 

I will let this Issue open until we copy them there, and let you know.

**Comment by wpoch** [comment]
Hi @adrianhsieh you could find the latest released dependencies on the MuleSoft Releases repository.

Regards,
